import numpy as np
import sounddevice as sd
import time
# generated by ChatGPT

def play_tone_rt(frequencies:list[float], duration:float, sample_rate=44100, amplitude=0.3):
    phase = 0

    def callback(outdata, frames, time_info, status):
        nonlocal phase
        t = (np.arange(frames) + phase) / sample_rate

        wave = sum(np.sin(2 * np.pi * f * t) for f in frequencies)
        wave *= amplitude / len(frequencies)

        outdata[:, 0] = wave
        phase += frames

    with sd.OutputStream(
        channels=1,
        callback=callback,
        samplerate=sample_rate,
        blocksize=1024
    ):
        time.sleep(duration)

if __name__ == "__main__":
    play_tone_rt([440, 442], 3.0)  # hear beating effect